### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by YilinLiu97** [bzcheeseman/pytorch-segnet#1]
Hi, @bzcheeseman  I found your implementation useful, but I encountered this error when I tried to train it:

Traceback (most recent call last):
  File "segnet.py", line 131, in <module>
    for j, data in enumerate(train_dataset, 1):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/yilin/pytorch-segnet/model/utils/__init__.py", line 75, in __getitem__
    path_to_target = self.annot[index]
IndexError: list index out of range

**Comment by bzcheeseman** [comment]
2 things:

1) Did you download the dataset?

2) I never actually tested this code by training it, I just tried out the model definition. I'd welcome a PR to fix the problem though!

**Comment by YilinLiu97** [comment]
Yes, I have downloaded the dataset.

Your implementation makes sense to me, except that this is a shallower one than the 'real' Segnet, right? I mean, in terms of the # of conv layers.

**Comment by bzcheeseman** [comment]
My best guess is that the data isn't being loaded quite right, so there may be an error somewhere in that implementation.

Yes, I believe so.

**Comment by YilinLiu97** [comment]
As long as the error isn't in the model implementation that would be totally fine to me. Thanks! good work
